import jsPDF from 'jspdf';
import { AssessmentResult, SUBJECT_LABELS, getFullName, PASS_THRESHOLD } from '@/types/assessment';
import { 
  getReadinessLabel, 
  getReadinessDescription 
} from '@/lib/assessmentUtils';
import { questionBank } from '@/data/questionBank';

export const generateResultsPDF = async (result: AssessmentResult): Promise<void> => {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  let yPos = margin;

  const primaryColor: [number, number, number] = [99, 102, 241];
  const textColor: [number, number, number] = [31, 41, 55];
  const mutedColor: [number, number, number] = [107, 114, 128];
  const successColor: [number, number, number] = [34, 197, 94];
  const dangerColor: [number, number, number] = [239, 68, 68];

  const setColor = (color: [number, number, number]) => {
    pdf.setTextColor(color[0], color[1], color[2]);
  };

  // Header
  pdf.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  pdf.rect(0, 0, pageWidth, 40, 'F');
  
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Tutor Proficiency Report', pageWidth / 2, 20, { align: 'center' });
  
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.text('ZaneTutors Assessment Results', pageWidth / 2, 30, { align: 'center' });

  yPos = 55;

  const tutorName = getFullName(result.studentInfo.firstName, result.studentInfo.lastName);
  
  setColor(textColor);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text(`Tutor: ${tutorName}`, margin, yPos);
  yPos += 8;
  
  setColor(mutedColor);
  pdf.setFontSize(10);
  pdf.text(`Email: ${result.studentInfo.email}`, margin, yPos);
  yPos += 6;
  pdf.text(`Date: ${new Date().toLocaleDateString()}`, margin, yPos);
  yPos += 12;

  // Overall Score
  setColor(textColor);
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Overall Score', margin, yPos);
  yPos += 10;

  pdf.setFontSize(36);
  const scoreColor = result.overallPassed ? successColor : dangerColor;
  setColor(scoreColor);
  pdf.text(`${result.finalReadinessScore}%`, margin, yPos);
  
  pdf.setFontSize(12);
  setColor(textColor);
  pdf.text(result.overallPassed ? 'PASSED' : 'DID NOT PASS', margin + 40, yPos - 8);
  pdf.setFontSize(10);
  setColor(mutedColor);
  pdf.text(getReadinessLabel(result.readinessLevel), margin + 40, yPos);
  yPos += 15;

  // Subject Breakdown
  setColor(textColor);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Subject Breakdown', margin, yPos);
  yPos += 8;

  result.subjectResults.forEach(sr => {
    setColor(textColor);
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'bold');
    pdf.text(SUBJECT_LABELS[sr.subject], margin, yPos);
    
    const passedLabel = sr.passed ? 'PASSED' : 'FAILED';
    setColor(sr.passed ? successColor : dangerColor);
    pdf.text(`${sr.percentage}% — ${passedLabel}`, margin + 60, yPos);
    
    setColor(mutedColor);
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`${sr.score}/${sr.totalQuestions} correct`, margin + 110, yPos);
    yPos += 7;

    if (sr.weakTopics.length > 0) {
      pdf.text(`Review: ${sr.weakTopics.join(', ')}`, margin + 5, yPos);
      yPos += 6;
    }
    yPos += 2;
  });

  yPos += 5;
  setColor(mutedColor);
  pdf.setFontSize(8);
  pdf.text(`Pass threshold: ${PASS_THRESHOLD}% per subject`, margin, yPos);
  yPos += 5;
  pdf.text('Generated by ZaneTutors Assessment Platform', margin, yPos);

  // Save
  const fileName = `ZaneTutors-Proficiency-${tutorName.replace(/\s+/g, '-')}.pdf`;
  pdf.save(fileName);
};
